### ISSUE TITLE
Update to AWS JAVA SDK v2

### ISSUE THREAD

**Issue by kevin-mcgoldrick** [intuit/Tank#117]
Utilize the new AWS SDK v2

```
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>${version.aws-sdk-bom}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
```

**Comment by dratler** [comment]
Hi @kevin-mcgoldrick ,
is this still open ?

**Comment by kevin-mcgoldrick** [comment]
> Hi @kevin-mcgoldrick ,
> is this still open ?

YES

**Comment by dratler** [comment]
Hi @kevin-mcgoldrick ,
I have created a [PR](https://github.com/intuit/Tank/pull/126l) foe this one , but I'm getting the following error :

` /Users/sdratler1/dev/opensource/Tank/api/src/main/java/com/intuit/tank/vm/settings/BaseCommonsXmlConfig.java:[51,9] cannot access org.apache.commons.lang.exception.NestableException
  class file for org.apache.commons.lang.exception.NestableException not found
`
