### ISSUE TITLE
Difficult to deploy in windows facing lot of issues 

### ISSUE THREAD

**Issue by rkravi123** [intuit/Tank#16]
Hi,

Is it possible to get .exe file instead of doing in babun or cygwin with lot of steps.

Regards,
Ravi

**Comment by rkravi123** [comment]
Hi,

I have deployed tank.war flle but unable to login to tank getting below messages.

could you please look into this issues.

**Comment by dangleton** [comment]
The messages did not get posted. Can you try post them or send them to me
