### ISSUE TITLE
JDK 11 Support

### ISSUE THREAD

**Issue by kevin-mcgoldrick** [intuit/Tank#75]

**Comment by lucianofecampos** [comment]
Hi @kevin-mcgoldrick, can I take this?

**Comment by nsinghal12** [comment]
@kevin-mcgoldrick I would like to pick this issue up. Please assign this to me. Also, I see there is a `develop` branch which seems current than `master` - let me know which branch to pick up for the upgrade.

**Comment by kevin-mcgoldrick** [comment]
develop is the latest work prepping for release. So please work from that branch.

**Comment by nsinghal12** [comment]
@kevin-mcgoldrick I have raised a PR for upgrading to JDK 11, however the following tests are failing: https://travis-ci.org/github/intuit/Tank/builds/737280311#L7267
