### ISSUE TITLE
Support a Non-linear ramp rate

### ISSUE THREAD

**Issue by kevin-mcgoldrick** [intuit/Tank#76]
### Existing linear ramp - single service
Is perfect for testing an individual service because all the calls go to a single destination, thus the load on that service scales linearly.
### Existing linear ramp - multi service
Once you consider multiple services than a problem appears.  For example a login as the first step to a set of scripts.  In the first minute you will start x news sessions, in the second minute you will start x new sessions, etc. This means the login service will go from zero to 100% test load in that one minute.  Beyond just login we see large scripts that call many services will spike services with few calls from zero to 100% load.
### Solution
Add a job configuration setting that allows you to choose a linear or non-linear ramp.
The non-linear ramp would shrink the wait between starts over half the ramp time, producing an S-curve to steady state. The S-curve from the client perspective, would produce the desired linear ramp on login and other rarely called endpoints.

**Comment by Nishant-sehgal** [comment]
@kevin-mcgoldrick  can you share  more details on it
