### ISSUE TITLE
Store script as an S3 object, not a database blob

### ISSUE THREAD

**Issue by kevin-mcgoldrick** [intuit/Tank#77]
### Existing
scripts are stored in ugly database blobs that abuse the database server on any input/output operation. This requires regular database restarts to recover memory and stop swapping.
### Ideal
scripts should be written as an S3 object with the bucket defined in the configuration, and the key should be stored in the database in place of the current reference.

**Comment by nishp77** [comment]
Sir, i'm new to this project but do you really mean that we make or add an object to s3?

**Comment by kevin-mcgoldrick** [comment]
Current TTO scripts enter the system at ~250MB.  That makes a better S3 object than a database blob. I'm open to other suggestions.
