### ISSUE TITLE
More Testing...  anything to achieve better code coverage

### ISSUE THREAD

**Issue by kevin-mcgoldrick** [intuit/Tank#88]

**Comment by t-gok** [comment]
@kevin-mcgoldrick can you assign this to me

**Comment by interactwithankush** [comment]
I would also like to contribute

**Comment by ratnamal** [comment]
@kevin-mcgoldrick Can you provide more details on what feature needs to be tested? I would like to contribute

**Comment by vaishakhvh** [comment]
Hi @kevin-mcgoldrick ,
Have taken the initiative to add test cases for data-access package. Have raised the [pull request](https://github.com/intuit/Tank/pull/115), please review and merge. 

_**Before making the code changes:**_
<img width="1008" alt="Screenshot 2020-10-02 at 4 14 49 PM" src="https://user-images.githubusercontent.com/72062381/94940082-a31a3d00-04f0-11eb-8733-09f4290dd135.png">

_**After adding test cases**_
<img width="989" alt="Screenshot 2020-10-02 at 8 37 28 PM" src="https://user-images.githubusercontent.com/72062381/94940159-bfb67500-04f0-11eb-9ce1-7f2969da6d99.png">

The code coverage has increased from 28% to 48% for data-access package. Please do let me know if I can work further on it.

**Comment by mani-sreekakula** [comment]
Hi @kevin-mcgoldrick ,
Have taken the initiative to add test cases for data-access package. Have raised the [pull request](https://github.com/intuit/Tank/pull/121), please review and merge.

**Before making the code changes:**
<img width="989" alt="94940159-bfb67500-04f0-11eb-9ce1-7f2969da6d99" src="https://user-images.githubusercontent.com/9196698/96759745-14fdec00-13f6-11eb-9363-6edc3627ebbd.png">
After adding test cases
<img width="1025" alt="codeCoverage" src="https://user-images.githubusercontent.com/9196698/96759787-221adb00-13f6-11eb-8c0c-e7be274077cc.png">

The code coverage has increased from 48% to 55% for data-access package.

**Comment by darshan-sj** [comment]
Hi @kevin-mcgoldrick ,
Have taken the initiative to add test cases for data-model package. Have raised the pull request, please review and merge.
#124 #123

**Comment by girijasameera** [comment]
@kevin-mcgoldrick is this open for this year's hacktoberfest? I'd like to contribute :)

**Comment by mani-sreekakula** [comment]
Hi @kevin-mcgoldrick ,
Have taken the initiative to add test cases for proxy-extension package. Have raised the pull request, please review and merge.

Before making the code changes:
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/9196698/196937155-b6d057bf-4d5f-4e88-803f-d939eb13f8aa.png">

After adding test cases:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/9196698/196936958-b0cd49a0-843e-4da0-957d-bf9dc477626d.png">


The code coverage has increased from 7% to 40% for proxy-extension package. Please do let me know if I can work further on it.
